### ISSUE TITLE
Invalid file extension

### ISSUE THREAD

**Issue by JakubGogola** [okkindel/sample#2]
[This](https://github.com/okkindel/sample/blob/master/sample.c) file is named `sample.c` what might suggest that this project is written in pure `C` language but when we open this file we can see it contains `iostream` import. It's C++ library so the file should have `*.cpp` extension. It's misleading for potential users of this library. You should fix it or consider rewriting project for some more popular, newer and easier to understand language like PHP or, what may @adimus11 suggest, CoffeScript.

**Comment by JakubGogola** [comment]
@okkindel any updates in terms of this issue? It's really urgent for me to resolved it ASAP!

**Comment by okkindel** [comment]
@JakubGogola  Please look at this pr. Let me know if it's okay.

https://github.com/okkindel/sample/pull/3

**Comment by JakubGogola** [comment]
Looks fine, I left a comment: https://github.com/okkindel/sample/pull/3#issuecomment-786191056
